#include<iostreamm.h>
#include<conio.h>
/*
class Employee{
int id;
int static count;  //This is static data member :
//int count;
public:
void setdata(void){
cout<<"Enter the Id "<<endl;
cin>>id;
count++;
}
void getdata(void){
cout<<"The employee id is "<<id<<" and this is employee number "<<count<<endl;
}
};
int Employee :: count;
void main()
{
clrscr();
Employee suraj,bhawani,lakshay;

suraj.setdata();
suraj.getdata();

bhawani.setdata();
bhawani.getdata();

lakshay.setdata();
lakshay.getdata();
*/
/*
class Employee{
int id;
int static count;  //2 This is static function :
//int count;
public:
void setdata(void){
cout<<"Enter the Id "<<endl;
cin>>id;
count++;
}
void getdata(void){
cout<<"The employee id is "<<id<<" and this is employee number "<<count<<endl;
}
static void  getcount(void){
cout<<"The value of count is " <<count<<endl;
}
};
int Employee :: count=1000;
void main()
{
clrscr();
Employee suraj,bhawani,lakshay;

suraj.setdata();
suraj.getdata();
Employee::getcount();

bhawani.setdata();
bhawani.getdata();
Employee::getcount();


lakshay.setdata();
lakshay.getdata();
Employee::getcount();

*/
getch();

}