		 //FIle IO
/*
The useful classes for working with files in c++ are:
1.fstreambase
ifstream-->derived from fstreambase
ofstream-->derived from fstreambase

*/
// In order work with files in c++ , you will have  to open it.primarily,
//there are 2 ways to open a file:
//1.using the constructor
//2. using the member function open() of the class

#include<iostream.h>
#include<fstreaam.h>
#include<conio.h>
void main()
{
clrscr();
// using write file


getch();
}