#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
/*int abhishek=24;
clrscr();
cout<<"The number is "<<abhishek;*/
/*int a,b; //the sum of two integer is ..................//////
cout<<"Enter a first number";
cin>>a;
cout<<"Enter a Second number";
cin>>b;
cout<<"The sum of number is "<<a+b;*/
//Using operator......
/*int a,b;
cout<<"Enter a first number";
cin>>a;
cout<<"Enter a Second number";
cin>>b;
cout<<"\nThe number is a+b is:" <<a+b;
cout<<"\nThe number is a-b is:" <<a-b;
cout<<"\nThe number is a*bis:" <<a*b;
cout<<"\nThe number is a/b is:" <<(float)a/b; */
//Using IF and ELSE**************************************//
/*int age;
cout<<"Enter the age"<<endl;
cin>>age;
if(age<=15){
cout<<"You are children"<<endl;
}
else{
cout<<"You are not a children:"<<endl;

} */
//Using SWITCH CASSE*************************************///
int age;
cout<<"Enter the age"<<endl;
cin>>age;
getch();

}