#include<iostream.h>
#include<conio.h>
#include<iomanip.h>
void main(){                   ///using iomanip..*****++
int a=45;
int b=4;
int c=12345;
clrscr();
cout<<"The value of a is "<<a<<endl;
cout<<"The value of a is "<<b<<endl;
cout<<"The value of a is "<<c<<endl;
cout<<"***************************************************"<<endl;
cout<<"The value of a is "<<setw(4)<<a<<endl;
cout<<"The value of a is "<<setw(4)<<b<<endl;
cout<<"The value of a is "<<setw(4)<<c<<endl;


getch();





}